CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AuditLogs" (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "Action" text NOT NULL,
    "Category" text NOT NULL,
    "EntityType" text,
    "EntityId" text,
    "IpAddress" text,
    "UserAgent" text,
    "Details" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "IsVerified" boolean NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "PermissionRole" (
    "PermissionsId" integer NOT NULL,
    "RolesId" integer NOT NULL,
    CONSTRAINT "PK_PermissionRole" PRIMARY KEY ("PermissionsId", "RolesId"),
    CONSTRAINT "FK_PermissionRole_Permissions_PermissionsId" FOREIGN KEY ("PermissionsId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PermissionRole_Roles_RolesId" FOREIGN KEY ("RolesId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ExternalLogins" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Provider" text NOT NULL,
    "ProviderUserId" text NOT NULL,
    CONSTRAINT "PK_ExternalLogins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExternalLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OtpVerifications" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CodeHash" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Attempts" integer NOT NULL,
    "Verified" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_OtpVerifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OtpVerifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "ReplacedByTokenId" uuid,
    "CreatedByIp" text,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoleUser" (
    "RolesId" integer NOT NULL,
    "UsersId" uuid NOT NULL,
    CONSTRAINT "PK_RoleUser" PRIMARY KEY ("RolesId", "UsersId"),
    CONSTRAINT "FK_RoleUser_Roles_RolesId" FOREIGN KEY ("RolesId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoleUser_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ExternalLogins_UserId" ON "ExternalLogins" ("UserId");

CREATE INDEX "IX_OtpVerifications_UserId" ON "OtpVerifications" ("UserId");

CREATE INDEX "IX_PermissionRole_RolesId" ON "PermissionRole" ("RolesId");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_RoleUser_UsersId" ON "RoleUser" ("UsersId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260918100226_InitialCreate', '9.0.20');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260918133424_RegisterDto', '9.0.20');

COMMIT;

